import { UserPersona, Wish, WishComment } from "./types";

export const USER_PERSONAS: UserPersona[] = [
  {
    id: "user-nobita",
    name: "Nobita N.",
    avatar: "nobita",
    role: "Daydreamer & Explorer",
    bio: "Always in need of a miracle gadget for homework, sports, or sleeping in.",
    themeColor: "#FFD447",
  },
  {
    id: "user-shizuka",
    name: "Shizuka M.",
    avatar: "shizuka",
    role: "Kind Neighbor & Pianist",
    bio: "Loves warm baths, sweet roasted sweet potatoes, and keeping the peace.",
    themeColor: "#FF4D4D",
  },
  {
    id: "user-gian",
    name: "Takeshi 'Gian' G.",
    avatar: "gian",
    role: "Neighborhood Champion",
    bio: "What's yours is mine, what's mine is mine! Secretly loves singing on trash cans.",
    themeColor: "#FFA500",
  },
  {
    id: "user-suneo",
    name: "Suneo H.",
    avatar: "suneo",
    role: "Tech & RC Model Collector",
    bio: "Boasting the latest high-tech toys, but always curious about the 4D pocket.",
    themeColor: "#7EC8E3",
  },
  {
    id: "user-doraemon",
    name: "Doraemon (Host)",
    avatar: "doraemon",
    role: "4D Pocket Caretaker",
    bio: "22nd-century feline robotic buddy. Fueled by red bean dorayaki pancakes.",
    themeColor: "#0A84FF",
  },
];

export const PRESET_GADGETS = [
  "Anywhere Door (Dokodemo Door)",
  "Bamboo-Copter (Take-copter)",
  "Time Machine (Time Machine)",
  "Memory Bread (Anki-pan)",
  "Small Light (Small Light)",
  "Big Light (Big Light)",
  "Translation Konjac (Honyaku Konnyaku)",
  "Time Cloth / Furoshiki (Time Furoshiki)",
  "Pass Loop (Toorinuhe Hoop)",
  "Dress-Up Camera (Kisekae Camera)",
  "Multiplying Liquid (Baibain)",
  "Gulliver Tunnel",
  "What-If Phone Booth (Moshimo Box)",
  "Air Cannon (Kuuki Hou)",
  "Compliment Robot",
  "Weather Box Controller",
];

export const GADGET_IMAGE_PRESETS = [
  {
    name: "Golden Sky Clouds",
    url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80",
  },
  {
    name: "Vintage Pendulum Clock",
    url: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=600&q=80",
  },
  {
    name: "Stack of Books & Notes",
    url: "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=600&q=80",
  },
  {
    name: "Delicious Warm Pastries",
    url: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=600&q=80",
  },
  {
    name: "Magical Starry Night",
    url: "https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&w=600&q=80",
  },
  {
    name: "World Map & Travel",
    url: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=600&q=80",
  },
  {
    name: "Outdoor Camping Lights",
    url: "https://images.unsplash.com/photo-1510312305653-8ed496efae75?auto=format&fit=crop&w=600&q=80",
  },
];

export const INITIAL_WISHES: Wish[] = [
  {
    id: "11111111-1111-1111-1111-111111111111",
    title: "Skip the Morning Traffic Rush Completely",
    description: "I wake up late almost every day and end up running in panic to make it to class before the morning bell rings. Can we have a door that opens directly into the school hallway?",
    category: "Travel & Time",
    status: "open",
    image_url: "https://images.unsplash.com/photo-1518241353330-0f7941c2d9b5?auto=format&fit=crop&w=600&q=80",
    creator_id: "user-nobita",
    creator_name: "Nobita N.",
    creator_avatar: "nobita",
    upvotes_count: 14,
    granted_gadget_name: null,
    granted_at: null,
    created_at: new Date(Date.now() - 3600000 * 8).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 8).toISOString(),
  },
  {
    id: "22222222-2222-2222-2222-222222222222",
    title: "Instant Memorization for Math and History Formulas",
    description: "Studying 40 pages of dates and trigonometry formulas the night before the final test is impossible. I wish I could just press notes onto toast and eat it to master the exam!",
    category: "Study & School",
    status: "open",
    image_url: "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=600&q=80",
    creator_id: "user-nobita",
    creator_name: "Nobita N.",
    creator_avatar: "nobita",
    upvotes_count: 21,
    granted_gadget_name: null,
    granted_at: null,
    created_at: new Date(Date.now() - 3600000 * 18).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 18).toISOString(),
  },
  {
    id: "33333333-3333-3333-3333-333333333333",
    title: "Restore My Grandmother's Antique Clock",
    description: "My grandmother has a beautiful antique pendulum clock that stopped ticking thirty years ago. Watchmakers say replacement parts are no longer made. I wish we could rewind its physical condition to brand new!",
    category: "Daily Life",
    status: "granted",
    image_url: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=600&q=80",
    creator_id: "user-shizuka",
    creator_name: "Shizuka M.",
    creator_avatar: "shizuka",
    upvotes_count: 35,
    granted_gadget_name: "Time Cloth (Time Furoshiki)",
    granted_at: new Date(Date.now() - 3600000 * 48).toISOString(),
    created_at: new Date(Date.now() - 3600000 * 52).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 48).toISOString(),
  },
  {
    id: "44444444-4444-4444-4444-444444444444",
    title: "Breeze Through the Sky on Pleasant Afternoons",
    description: "Walking through crowded sidewalks is exhausting. Imagine strapping a tiny gentle propeller to your hat and cruising over the rooftops with the wind in your face!",
    category: "Travel & Time",
    status: "open",
    image_url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=600&q=80",
    creator_id: "user-suneo",
    creator_name: "Suneo H.",
    creator_avatar: "suneo",
    upvotes_count: 18,
    granted_gadget_name: null,
    granted_at: null,
    created_at: new Date(Date.now() - 3600000 * 24).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 24).toISOString(),
  },
  {
    id: "55555555-5555-5555-5555-555555555555",
    title: "An Endless Tray of Fresh Sweet Bean Pastries",
    description: "Whenever we buy a box of warm red bean pancakes, they vanish in 2 minutes flat! There should be a device that doubles whatever food you put in front of it every few minutes.",
    category: "Food & Dorayaki",
    status: "granted",
    image_url: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=600&q=80",
    creator_id: "user-doraemon",
    creator_name: "Doraemon (Host)",
    creator_avatar: "doraemon",
    upvotes_count: 42,
    granted_gadget_name: "Multiplying Mirror & Liquid",
    granted_at: new Date(Date.now() - 3600000 * 20).toISOString(),
    created_at: new Date(Date.now() - 3600000 * 30).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 20).toISOString(),
  },
  {
    id: "66666666-6666-6666-6666-666666666666",
    title: "Speak Any Language Instantly While Traveling",
    description: "I want to converse fluently with people all around the world without spending 5 years with grammar flashcards. A sweet jelly candy that translates instantly when you swallow it!",
    category: "Secret Gadgets",
    status: "open",
    image_url: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=600&q=80",
    creator_id: "user-gian",
    creator_name: "Takeshi 'Gian' G.",
    creator_avatar: "gian",
    upvotes_count: 27,
    granted_gadget_name: null,
    granted_at: null,
    created_at: new Date(Date.now() - 3600000 * 36).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 36).toISOString(),
  },
  {
    id: "77777777-7777-7777-7777-777777777777",
    title: "Miniaturize Camping Gear to Fit into a Keychain",
    description: "Tents, sleeping bags, and heavy cookware take up so much trunk space. We need a flashlight that shrinks physical objects when illuminated with soft yellow beam!",
    category: "Secret Gadgets",
    status: "open",
    image_url: "https://images.unsplash.com/photo-1510312305653-8ed496efae75?auto=format&fit=crop&w=600&q=80",
    creator_id: "user-shizuka",
    creator_name: "Shizuka M.",
    creator_avatar: "shizuka",
    upvotes_count: 19,
    granted_gadget_name: null,
    granted_at: null,
    created_at: new Date(Date.now() - 3600000 * 12).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 12).toISOString(),
  },
];

export const INITIAL_COMMENTS: WishComment[] = [
  {
    id: "c1",
    wish_id: "11111111-1111-1111-1111-111111111111",
    user_id: "user-doraemon",
    user_name: "Doraemon (Host)",
    user_avatar: "doraemon",
    content: "I reached into the 4D pocket and found the Anywhere Door! Just rotate the knob and imagine your destination clearly.",
    is_gadget_solution: true,
    gadget_name: "Anywhere Door (Dokodemo Door)",
    created_at: new Date(Date.now() - 3600000 * 6).toISOString(),
  },
  {
    id: "c2",
    wish_id: "11111111-1111-1111-1111-111111111111",
    user_id: "user-shizuka",
    user_name: "Shizuka M.",
    user_avatar: "shizuka",
    content: "Please make sure Nobita doesn't open the door while someone is playing the violin or taking a bath! 🌸",
    is_gadget_solution: false,
    gadget_name: null,
    created_at: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
  {
    id: "c3",
    wish_id: "22222222-2222-2222-2222-222222222222",
    user_id: "user-doraemon",
    user_name: "Doraemon (Host)",
    user_avatar: "doraemon",
    content: "Here is Memory Bread (Anki-pan)! Press the slice on your book and eat. But if your stomach gets upset, the formulas disappear!",
    is_gadget_solution: true,
    gadget_name: "Memory Bread (Anki-pan)",
    created_at: new Date(Date.now() - 3600000 * 14).toISOString(),
  },
  {
    id: "c4",
    wish_id: "33333333-3333-3333-3333-333333333333",
    user_id: "user-doraemon",
    user_name: "Doraemon (Host)",
    user_avatar: "doraemon",
    content: "Wish officially granted! We wrapped the clock in the red side of the Time Furoshiki (Time Cloth). The brass pendulum now shines like new!",
    is_gadget_solution: true,
    gadget_name: "Time Cloth (Time Furoshiki)",
    created_at: new Date(Date.now() - 3600000 * 48).toISOString(),
  },
  {
    id: "c5",
    wish_id: "55555555-5555-5555-5555-555555555555",
    user_id: "user-nobita",
    user_name: "Nobita N.",
    user_avatar: "nobita",
    content: "Doraemon ate 30 dorayaki all by himself after multiplying them! His belly was so round he had to roll home!",
    is_gadget_solution: false,
    gadget_name: null,
    created_at: new Date(Date.now() - 3600000 * 22).toISOString(),
  },
];
